os: linux
language: elixir
elixir: 1.11.3
otp_release: 23.1.2
cache:
  directories:
    - _build
    - deps
script:
  - mix format --check-formatted || travis_terminate 1
  - mix test --trace || travis_terminate 1
  - mix smoke_test || travis_terminate 1
